name: Render Template
description: Renders file based on template and passed variables

author: Lucas Freitas <lucas@lucasfreitas.com.br>

branding:
  icon: file-text
  color: purple

inputs:
  template:
    description: Path to template
    required: true

  vars:
    description: Variables to use in template
    required: false

  result_path:
    description: Desired path to result file (optional)
    required: false

outputs:
  result:
    description: Rendered file content

runs:
  using: docker
  image: 'docker://lukeshard/render-template:latest'
  args:
    - ${{ inputs.vars }}
    - ${{ inputs.template }}
